<?php

namespace AppBundle\Repository;

/**
 * LoadInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
