<?php

namespace AppBundle\Repository;

/**
 * TrackOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
