<?php

namespace UserBundle\Repository;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @param $role
     * @return User[]|null
     */
    public function findByRole($role){
        $qb = $this->_em->createQueryBuilder();
        
        if ($role=='ROLE_USER'){
            $qb->select('u')
                ->from('UserBundle:User', 'u')
                ->where('u.roles = :roles1 OR u.roles = :roles2')
                ->setParameter('roles1', 'a:0:{}')
                ->setParameter('roles2', 'a:1:{i:0;s:0:"";}')
            ;
        }else{
            $qb->select('u')
                ->from('UserBundle:User', 'u')
                ->where('u.roles LIKE :roles')
                ->setParameter('roles', '%"'.$role.'"%')
            ;
        }
        
        
    
        return $qb->getQuery()->getResult();
    }
    
    /**
     * @return User[]|null
     */
    public function getRegisteredUsers(){
        return $this->findByRole('ROLE_USER');
    }
    
    /**
     * @return User[]|null
     */
    public function getBoardUsers(){
        return $this->findByRole('ROLE_BOARD');
    }
    
    /**
     * @return User[]|null
     */
    public function getStaffAndAdminUsers(){
        return array_merge($this->findByRole('ROLE_ADMIN'),$this->findByRole('ROLE_STAFF'));
    }

   
}
